# Generated by Django 5.2 on 2025-04-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='"contact"',
        ),
    ]
