# Generated by Django 5.2 on 2025-04-21 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entrega_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
