# Generated by Django 5.2 on 2025-04-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_entrega_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='entrega_date',
        ),
    ]
