# Generated by Django 5.2 on 2025-04-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_category_contact_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='"category"',
        ),
    ]
