# Generated by Django 5.2 on 2025-04-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_category_options_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
